### ISSUE TITLE
Collegamento con mongodb (Fabio)

### ISSUE THREAD

**Issue by NamelessKing** [FabioDanesin/Ingegneria-del-software-2021#10]
issue uguale #9

**Comment by FabioDanesin** [comment]
Trovata la sintassi della select e dell'update. Posto un pezzo di codice sorgente typescript + javascript entro oggi.

**Comment by FabioDanesin** [comment]
Alla fine non posto typescript. Posto solo JS commentato. le modifiche si trovano nel file update_user_coordinates.js dentro alla cartella src/scripts
