### ISSUE TITLE
Mini guida avvio BE per i ragazzi

### ISSUE THREAD

**Issue by NamelessKing** [FabioDanesin/Ingegneria-del-software-2021#12]
Guida che permetta di capire come avviare il BE

**Comment by FabioDanesin** [comment]
L'avvio del backend dell'applicazione è stato scritto nel main branch.

**Comment by NamelessKing** [comment]
> L'avvio del backend dell'applicazione è stato scritto nel main branch.

ok bisogna che diamo un occhiata assieme e provare ad aviarlo nell'ambiente di qualcuno che non lo ha ancora fatto
